### ISSUE TITLE
Correct error while retrieving IP address from interface (e.g. TC #183484)

### ISSUE THREAD

**Issue by rdkdd** [spiceqa/tp-spice#33]
During creating of guest VM NetError emerges

from job.log:

```
15:49:09 DEBUG| Removing VM guest NIC ifname t0-ijn0H9 from bridge 
15:49:09 DEBUG| Host does not support OpenVSwitch: Command 'ovs-vswitchd' could not be found in any of the PATH dirs: ['/usr/lib64/qt-3.3/bin', '/bin', '/sbin', '/usr/bin', '/usr/local/sbin', '/root/bin', '/usr/libexec', '/mnt/tests/spice/qe-tests/avocado/scripts', '/mnt/tests/spice/qe-tests/avocado-vt/virttest', '/usr/sbin', '/usr/local/bin']
15:49:09 ERROR| Fail to create qemu command:
15:49:09 ERROR| Original Traceback (most recent call last):
  File "/mnt/tests/spice/qe-tests/avocado-vt/virttest/qemu_vm.py", line 2637, in create
    self.devices = self.make_create_command()
  File "/mnt/tests/spice/qe-tests/avocado-vt/virttest/qemu_vm.py", line 2018, in make_create_command
    cmd += add_spice()
  File "/mnt/tests/spice/qe-tests/avocado-vt/virttest/qemu_vm.py", line 1031, in add_spice
    s_subj += utils_net.get_host_ip_address(self.params)
  File "/mnt/tests/spice/qe-tests/avocado-vt/virttest/utils_net.py", line 3017, in get_host_ip_address
    host_ip = get_ip_address_by_interface(params.get('netdst'))
  File "/mnt/tests/spice/qe-tests/avocado-vt/virttest/utils_net.py", line 3006, in get_ip_address_by_interface
    "Error while retrieving IP address from interface %s." % ifname)
NetError: Error while retrieving IP address from interface .
```

**Comment by Andrei-Stepanov** [comment]
Could you please try this replacement ?  /mnt/tests/spice/qe-tests/avocado-vt/virttest/utils_net.py", line 3006

```
def get_host_ip_address(params):
    """
    returns ip address of host specified in host_ip_addr parameter If provided
    otherwise ip address on interface specified in netdst parameter is returned
    :param params
    """
    key = 'host_ip_addr'
    host_ip = params.get(key, None)
    if host_ip:
        logging.debug("Use IP address at config %s=%s", key, host_ip)
        return host_ip
    net_dev = params.get('netdst')
    if not net_dev:
        net_dev = get_host_iface()
    if not net_dev:
        raise NetError("Error while retrieving IP address for host.")
    net_dev = net_dev[0] # Use the first network iface in the list.
    logging.warning("No IP address of host was provided, using IP address"
                    " on %s interface", str(net_dev))
    host_ip = get_ip_address_by_interface(net_dev)
    return host_ip
```

**Comment by rdkdd** [comment]
Thanks Andrei!
