### ISSUE TITLE
Handle negative option in copy-paste tests

### ISSUE THREAD

**Issue by rdkdd** [spiceqa/tp-spice#39]
Avocado returns ERROR if negative test case is run. It does not take `negative` option in cfg file into consideration.

Sampe traceback (TC #282134):

```
Reproduced traceback from: /mnt/tests/spice/qe-tests/avocado-vt/avocado_vt/test.py:420
Traceback (most recent call last):
  File "/mnt/tests/spice/qe-tests/avocado-vt/avocado_vt/test.py", line 196, in runTest
    self._runTest()
  File "/mnt/tests/spice/qe-tests/avocado-vt/avocado_vt/test.py", line 337, in _runTest
    run_func(self, params, env)
  File "/mnt/tests/spice/qe-tests/avocado-data/avocado-vt/test-providers.d/downloads/io-github-spiceqa-spice/spice/tests/rv_copypaste.py", line 67, in run
    text = act.cb2text(dst)
  File "/mnt/tests/spice/qe-tests/avocado-data/avocado-vt/test-providers.d/downloads/io-github-spiceqa-spice/spice/lib/act2.py", line 74, in __call__
    return action(vmi, *args, **kwargs)
  File "/mnt/tests/spice/qe-tests/avocado-data/avocado-vt/test-providers.d/downloads/io-github-spiceqa-spice/spice/lib/vm_actions_linux.py", line 826, in cb2text
    text = act.run(vmi, cmd)
  File "/mnt/tests/spice/qe-tests/avocado-data/avocado-vt/test-providers.d/downloads/io-github-spiceqa-spice/spice/lib/act2.py", line 74, in __call__
    return action(vmi, *args, **kwargs)
  File "/mnt/tests/spice/qe-tests/avocado-data/avocado-vt/test-providers.d/downloads/io-github-spiceqa-spice/spice/lib/vm_actions.py", line 53, in run
    out = ssn.cmd(cmdline, **kwargs)
  File "/usr/lib/python2.7/site-packages/aexpect/client.py", line 1211, in cmd
    raise ShellCmdError(cmd, s, o)
ShellCmdError: Shell command failed: '/home/test/tp-spice/helper_cb.py --cb2stdout'    (status: 1,    output: 'Traceback (most recent call last):\n  File "/home/test/tp-spice/helper_cb.py", line 123, in <module>\n    raise Exception("Clipboard is empty.")\nException: Clipboard is empty.\n')

Traceback (most recent call last):

  File "/mnt/tests/spice/qe-tests/avocado-vt/avocado_vt/test.py", line 434, in _run_avocado
    raise test_exception

ShellCmdError: Shell command failed: '/home/test/tp-spice/helper_cb.py --cb2stdout'    (status: 1,    output: 'Traceback (most recent call last):\n  File "/home/test/tp-spice/helper_cb.py", line 123, in <module>\n    raise Exception("Clipboard is empty.")\nException: Clipboard is empty.\n')

ERROR 1-cmdline_test.rv_copypaste.282134 -> ShellCmdError: Shell command failed: '/home/test/tp-spice/helper_cb.py --cb2stdout'    (status: 1,    output: 'Traceback (most recent call last):\n  File "/home/test/tp-spice/helper_cb.py", line 123, in <module>\n    raise Exception("Clipboard is empty.")\nException: Clipboard is empty.\n')

```

**Comment by rdkdd** [comment]
Solved by https://github.com/spiceqa/tp-spice/commit/beee07a64efa8676cc1998c74feebc399b9a306d. Closing this.
Thanks @Andrei-Stepanov !
